### PR TITLE
Designed New Twitter Banner for Opsdroid

### PR DESCRIPTION
**Pull request by MohamedMafaz**

### CODE REVIEW

**Comment by MohamedMafaz** [comment]
Hey, Are you satisfied with my design

**Comment by jacobtomlinson** [comment]
Thanks for taking the time to work on this. 

I don't think we need the extra "AI person" graphic that you've added. If you removed that and centred the Opsdroid logo it would look much better.

**Comment by MohamedMafaz** [comment]
I updated the Design. Please Check it out & let me know

**Comment by jacobtomlinson** [comment]
Looks great! Could I also ask you to rename the file. If you check other files in that folder that are all lowercase with dashes. So something like `opsdroid-chatbot-framework-banner.png`.

**Comment by MohamedMafaz** [comment]
I Updated. Check it out

**Review by jacobtomlinson — APPROVED** [review]
Awesome many thanks!

**Comment by jacobtomlinson** [comment]
I used this banner on Twitter 😊

https://twitter.com/opsdroid

**Pull request merged**
