### PR TITLE
Added new opsdroid banner ad

### PR DESCRIPTION
**Pull request by sakkshm**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Good work thanks for this!

We love to thank contributors by sending them [opsdroid stickers](https://medium.com/opsdroid/contributor-sticker-packs-738058ceda59)! Fill in the [claim form](https://forms.gle/iQZV9DjkaUiSaDXK6) to get yours!

**Comment by sakkshm** [comment]
Thank you!
Please tell me what else I can add so I might help and also get some hacktoberfest points!

**Comment by jacobtomlinson** [comment]
Sure! Are you just interested in design and graphics or are you up for looking at some Python coding too?

**Comment by sakkshm** [comment]
I can do a little bit of graphics/design 
I am not good with python but I can do web related(js,html,css, etc) things for you!

**Comment by jacobtomlinson** [comment]
Ok sure! You should have a look at the [opsdroid website code](https://github.com/opsdroid/opsdroid.github.io) and [opsdroid-web](https://github.com/opsdroid/opsdroid-web), those are both html/css/js projects.

**Pull request merged**
