### PR TITLE
Sticker entry iice89

### PR DESCRIPTION
**Pull request by iiCe89**
I have created folder Sticker_submission and added my sticker entry :) Good luck and great comp!

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
This is awesome thanks so much!

**Comment by iiCe89** [comment]
No problem @jacobtomlinson if you need help with anything drop me DM on twitter or @ me in here

**Comment by jacobtomlinson** [comment]
Thanks @iiCe89. I'm sure this design will do well in the competition! My only bit of feedback is that this year they have "fest" in a different font in quite a lot of the branding. This may be more recognisable for 2019.

Also I've just updated the [terms of the competition](https://github.com/opsdroid/style-guidelines/issues/3) to say that you agree that we can use the logo for stuff. Could you just have a look and confirm you are happy with it?

**Comment by iiCe89** [comment]
im happy :)

**Comment by jacobtomlinson** [comment]
Make sure you fill in the [claim form](https://forms.gle/iQZV9DjkaUiSaDXK6) to get your stickers!

**Pull request merged**
