### PR TITLE
Add logo cloth version

### PR DESCRIPTION
**Pull request by Amchuz**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for taking the time to raise this @Amchuz.

It looks like you have applied a filter to the existing logo. But it looks like there are some strange artifacts going on.

Could you share a little more about what you intended this to be used for?

**Comment by Amchuz** [comment]
@jacobtomlinson I got this repo from another site and was said that we could edit the logo to make other versions to contribute to this project. I am really sorry if I got it all wrong.

**Comment by jacobtomlinson** [comment]
>  I got this repo from another site

Could you share which site?

> [...] said that we could edit the logo to make other versions to contribute to this project

Sure, we definitely like logo variations. 

For example we have a maintainers logo [here](https://github.com/opsdroid/style-guidelines/blob/master/logos/logo-maintainer-light.png). We use this logo for the [maintainer team in GitHub](https://github.com/orgs/opsdroid/teams/maintainers).

However I don't think you've given any thought to how we would use your logo. What is its purpose? Where could we use it?

> I am really sorry if I got it all wrong.

Please don't be sorry! We appreciate contributions here. However we prefer to discuss things in issues first. 

Generally we only accept PRs which close an open issue that a maintainer has said "yes we should do this".

**Comment by Amchuz** [comment]
I will keep that in mind. Thank you so much for your time.

**Pull request closed without merging**
