### PR TITLE
Masked Logos

### PR DESCRIPTION
**Pull request by Kanishk-K-U**
I have created COVID-19 masked version of opsdroid logos.

### CODE REVIEW

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
Thanks for proposing this @Kanishk-K-U. I'm not entirely sure how we would use these but I quite like them.

A few notes on your PR that will need to be addressed:
- You seem to have deleted a bunch of files here. You probably didn't mean to do that.
- You have edited a bunch of unrelated files also, I expect this was unintentional too.
- The README you added links to files in your forks. It would be best to use relative links here so it works in any repo.

**Comment by Kanishk-K-U** [comment]
Thnaks but I haven't deleted any files in this repo.

**Comment by Kanishk-K-U** [comment]
Screenshot 2021-05-25 at 2 50 20 PM

**Comment by Kanishk-K-U** [comment]
check now I have removed all other stuff.

**Comment by Kanishk-K-U** [comment]
Updated all changes.

**Comment by jacobtomlinson** [comment]
Thanks for fixing the README. 

It still looks like this PR unintentionally deletes a bunch of files though.

**Pull request closed without merging**
