### PR TITLE
Updated SVG file

### PR DESCRIPTION
**Pull request by omkhulbe**
updated the .svg file who's P and R was not looking properly.

### CODE REVIEW

**Comment by omkhulbe** [comment]
@jacobtomlinson Please checkout new .svg file.

**Comment by jacobtomlinson** [comment]
Thanks for fixing that

**Comment by omkhulbe** [comment]
@jacobtomlinson is the sticker event is still going on?? Because I have filled that form

**Comment by jacobtomlinson** [comment]
Due to high demand we only send stickers for PRs which solve an open issue.

**Comment by omkhulbe** [comment]
So since I have made logo am I eligible to win the stickers

**Comment by omkhulbe** [comment]
Because as mentioned in the article logo will also be considered.

**Pull request merged**
